<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nexus.TaskManagement\Nexus.TaskManagement.csproj" />
    <ProjectReference Include="..\Notifications.Application\Notifications.Application.csproj" />
  </ItemGroup>

</Project>
